// export const mockCategories = [
//   { id: 1, name: "Cultural", slug: "cultural" },
//   { id: 2, name: "Seasonal", slug: "seasonal" },
//   { id: 3, name: "Adventure", slug: "adventure" },
//   { id: 4, name: "Food", slug: "food" },
//   { id: 5, name: "Budget Travel", slug: "budget" },
//   { id: 6, name: "Photography", slug: "photography" },
//   { id: 7, name: "Wildlife", slug: "wildlife" },
//   { id: 8, name: "Road Trips", slug: "road-trips" },
// ];

import { Category, Country } from "../_types";

// Sample Categories
export const mockBlogCategories: Category[] = [
  {
    id: 1,
    name: "Travel",
    slug: "travel",
    description: "Experiences and destinations for all types of travelers",
  },
  {
    id: 2,
    name: "Tips",
    slug: "tips",
    description: "Practical guides and recommendations to improve your travels",
  },
  {
    id: 3,
    name: "Gastronomy",
    slug: "gastronomy",
    description:
      "Discover flavors and culinary traditions from around the world",
  },
  {
    id: 4,
    name: "Adventure",
    slug: "adventure",
    description: "Exciting experiences and extreme sports",
  },
];

export const mockCountries: Country[] = [
  {
    id: 1,
    name: "Thailand",
    slug: "thailand",
    code: "TH",
    phoneCode: "+66",
    currency: {
      code: "THB",
      symbol: "฿",
      name: "Thai Baht",
    },
    languages: [
      {
        code: "th",
        name: "Thai",
        native: "ไทย",
        primary: true,
      },
      {
        code: "en",
        name: "English",
        native: "English",
        primary: false,
      },
    ],
    flag: "🇹🇭",
    active: true,
    metadata: {
      continent: "Asia",
      region: "Southeast Asia",
      capital: "Bangkok",
      timezone: "UTC+7",
      population: 69950850,
      area: 513120,
      coordinates: {
        latitude: 15.87,
        longitude: 100.9925,
      },
    },
  },
  {
    id: 2,
    name: "Switzerland",
    slug: "switzerland",
    code: "CH",
    phoneCode: "+41",
    currency: {
      code: "CHF",
      symbol: "Fr",
      name: "Swiss Franc",
    },
    languages: [
      {
        code: "de",
        name: "German",
        native: "Deutsch",
        primary: true,
      },
      {
        code: "fr",
        name: "French",
        native: "Français",
        primary: false,
      },
      {
        code: "it",
        name: "Italian",
        native: "Italiano",
        primary: false,
      },
    ],
    flag: "🇨🇭",
    active: true,
    metadata: {
      continent: "Europe",
      region: "Central Europe",
      capital: "Bern",
      timezone: "UTC+1",
      population: 8654622,
      area: 41277,
      coordinates: {
        latitude: 46.8182,
        longitude: 8.2275,
      },
    },
  },
  {
    id: 3,
    name: "Indonesia",
    slug: "indonesia",
    code: "ID",
    phoneCode: "+62",
    currency: {
      code: "IDR",
      symbol: "Rp",
      name: "Indonesian Rupiah",
    },
    languages: [
      {
        code: "id",
        name: "Indonesian",
        native: "Bahasa Indonesia",
        primary: true,
      },
      {
        code: "en",
        name: "English",
        native: "English",
        primary: false,
      },
    ],
    flag: "🇮🇩",
    active: true,
    metadata: {
      continent: "Asia",
      region: "Southeast Asia",
      capital: "Jakarta",
      timezone: "UTC+7",
      population: 273523615,
      area: 1904569,
      coordinates: {
        latitude: -0.7893,
        longitude: 113.9213,
      },
    },
  },
  {
    id: 4,
    name: "Japan",
    slug: "japan",
    code: "JP",
    phoneCode: "+81",
    currency: {
      code: "JPY",
      symbol: "¥",
      name: "Japanese Yen",
    },
    languages: [
      {
        code: "ja",
        name: "Japanese",
        native: "日本語",
        primary: true,
      },
      {
        code: "en",
        name: "English",
        native: "English",
        primary: false,
      },
    ],
    flag: "🇯🇵",
    active: true,
    metadata: {
      continent: "Asia",
      region: "East Asia",
      capital: "Tokyo",
      timezone: "UTC+9",
      population: 125836021,
      area: 377975,
      coordinates: {
        latitude: 36.2048,
        longitude: 138.2529,
      },
    },
  },
  {
    id: 5,
    name: "Tanzania",
    slug: "tanzania",
    code: "TZ",
    phoneCode: "+255",
    currency: {
      code: "TZS",
      symbol: "TSh",
      name: "Tanzanian Shilling",
    },
    languages: [
      {
        code: "sw",
        name: "Swahili",
        native: "Kiswahili",
        primary: true,
      },
      {
        code: "en",
        name: "English",
        native: "English",
        primary: false,
      },
    ],
    flag: "🇹🇿",
    active: true,
    metadata: {
      continent: "Africa",
      region: "East Africa",
      capital: "Dodoma",
      timezone: "UTC+3",
      population: 59734218,
      area: 945087,
      coordinates: {
        latitude: -6.369028,
        longitude: 34.888822,
      },
    },
  },
  {
    id: 6,
    name: "Greece",
    slug: "greece",
    code: "GR",
    phoneCode: "+30",
    currency: {
      code: "EUR",
      symbol: "€",
      name: "Euro",
    },
    languages: [
      {
        code: "el",
        name: "Greek",
        native: "Ελληνικά",
        primary: true,
      },
      {
        code: "en",
        name: "English",
        native: "English",
        primary: false,
      },
    ],
    flag: "🇬🇷",
    active: true,
    metadata: {
      continent: "Europe",
      region: "Southern Europe",
      capital: "Athens",
      timezone: "UTC+2",
      population: 10423054,
      area: 131957,
      coordinates: {
        latitude: 39.0742,
        longitude: 21.8243,
      },
    },
  },
  {
    id: 7,
    name: "Peru",
    slug: "peru",
    code: "PE",
    phoneCode: "+51",
    currency: {
      code: "PEN",
      symbol: "S/.",
      name: "Peruvian Sol",
    },
    languages: [
      {
        code: "es",
        name: "Spanish",
        native: "Español",
        primary: true,
      },
      {
        code: "qu",
        name: "Quechua",
        native: "Runa Simi",
        primary: false,
      },
    ],
    flag: "🇵🇪",
    active: true,
    metadata: {
      continent: "South America",
      region: "Western South America",
      capital: "Lima",
      timezone: "UTC-5",
      population: 32971854,
      area: 1285216,
      coordinates: {
        latitude: -9.19,
        longitude: -75.0152,
      },
    },
  },
  {
    id: 8,
    name: "Iceland",
    slug: "iceland",
    code: "IS",
    phoneCode: "+354",
    currency: {
      code: "ISK",
      symbol: "kr",
      name: "Icelandic Króna",
    },
    languages: [
      {
        code: "is",
        name: "Icelandic",
        native: "Íslenska",
        primary: true,
      },
      {
        code: "en",
        name: "English",
        native: "English",
        primary: false,
      },
    ],
    flag: "🇮🇸",
    active: true,
    metadata: {
      continent: "Europe",
      region: "Northern Europe",
      capital: "Reykjavik",
      timezone: "UTC+0",
      population: 364134,
      area: 103000,
      coordinates: {
        latitude: 64.9631,
        longitude: -19.0208,
      },
    },
  },
  {
    id: 9,
    name: "Vietnam",
    slug: "vietnam",
    code: "VN",
    phoneCode: "+84",
    currency: {
      code: "VND",
      symbol: "₫",
      name: "Vietnamese Dong",
    },
    languages: [
      {
        code: "vi",
        name: "Vietnamese",
        native: "Tiếng Việt",
        primary: true,
      },
      {
        code: "en",
        name: "English",
        native: "English",
        primary: false,
      },
    ],
    flag: "🇻🇳",
    active: true,
    metadata: {
      continent: "Asia",
      region: "Southeast Asia",
      capital: "Hanoi",
      timezone: "UTC+7",
      population: 97338579,
      area: 331212,
      coordinates: {
        latitude: 14.0583,
        longitude: 108.2772,
      },
    },
  },
  {
    id: 10,
    name: "Italy",
    slug: "italy",
    code: "IT",
    phoneCode: "+39",
    currency: {
      code: "EUR",
      symbol: "€",
      name: "Euro",
    },
    languages: [
      {
        code: "it",
        name: "Italian",
        native: "Italiano",
        primary: true,
      },
      {
        code: "en",
        name: "English",
        native: "English",
        primary: false,
      },
    ],
    flag: "🇮🇹",
    active: true,
    metadata: {
      continent: "Europe",
      region: "Southern Europe",
      capital: "Rome",
      timezone: "UTC+1",
      population: 60461826,
      area: 301340,
      coordinates: {
        latitude: 41.8719,
        longitude: 12.5674,
      },
    },
  },
  {
    id: 11,
    name: "Norway",
    slug: "norway",
    code: "NO",
    phoneCode: "+47",
    currency: {
      code: "NOK",
      symbol: "kr",
      name: "Norwegian Krone",
    },
    languages: [
      {
        code: "no",
        name: "Norwegian",
        native: "Norsk",
        primary: true,
      },
      {
        code: "en",
        name: "English",
        native: "English",
        primary: false,
      },
    ],
    flag: "🇳🇴",
    active: true,
    metadata: {
      continent: "Europe",
      region: "Northern Europe",
      capital: "Oslo",
      timezone: "UTC+1",
      population: 5421241,
      area: 385207,
      coordinates: {
        latitude: 60.472,
        longitude: 8.4689,
      },
    },
  },
  {
    id: 12,
    name: "Greenland",
    slug: "greenland",
    code: "GL",
    phoneCode: "+299",
    currency: {
      code: "DKK",
      symbol: "kr",
      name: "Danish Krone",
    },
    languages: [
      {
        code: "kl",
        name: "Greenlandic",
        native: "Kalaallisut",
        primary: true,
      },
      {
        code: "da",
        name: "Danish",
        native: "Dansk",
        primary: false,
      },
    ],
    flag: "🇬🇱",
    active: true,
    metadata: {
      continent: "North America",
      region: "Northern America",
      capital: "Nuuk",
      timezone: "UTC-3",
      population: 56421,
      area: 2166086,
      coordinates: {
        latitude: 71.7069,
        longitude: -42.6043,
      },
    },
  },
  {
    id: 13,
    name: "United Arab Emirates",
    slug: "united-arab-emirates",
    code: "AE",
    phoneCode: "+971",
    currency: {
      code: "AED",
      symbol: "د.إ",
      name: "UAE Dirham",
    },
    languages: [
      {
        code: "ar",
        name: "Arabic",
        native: "العربية",
        primary: true,
      },
      {
        code: "en",
        name: "English",
        native: "English",
        primary: false,
      },
    ],
    flag: "🇦🇪",
    active: true,
    metadata: {
      continent: "Asia",
      region: "Western Asia",
      capital: "Abu Dhabi",
      timezone: "UTC+4",
      population: 9890402,
      area: 83600,
      coordinates: {
        latitude: 23.4241,
        longitude: 53.8478,
      },
    },
  },
  {
    id: 14,
    name: "Australia",
    slug: "australia",
    code: "AU",
    phoneCode: "+61",
    currency: {
      code: "AUD",
      symbol: "$",
      name: "Australian Dollar",
    },
    languages: [
      {
        code: "en",
        name: "English",
        native: "English",
        primary: true,
      },
    ],
    flag: "🇦🇺",
    active: true,
    metadata: {
      continent: "Oceania",
      region: "Pacific",
      capital: "Canberra",
      timezone: "UTC+10",
      population: 25499884,
      area: 7692024,
      coordinates: {
        latitude: -25.2744,
        longitude: 133.7751,
      },
    },
  },
];
