import type { Metadata } from "next";
import classnames from "classnames/bind";
import "@/app/_styles/globals.scss";
import { raleway } from "./_fonts";
import { Header, Footer } from "@/app/_components";
import { footerData, headerData } from "@/app/_lib/data";
import styles from "./layout.module.scss";

const cx = classnames.bind(styles);

export const metadata: Metadata = {
  title: "Kotahi",
  description: "Generated by create next app",
};

const alwaysScrolledRoutes = ["/travel-guides", "/travel-guides/*"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cx(raleway.className, "layout")}>
        <Header
          data={headerData.data}
          frontPageID={headerData.frontPageID}
          alwaysScrolledRoutes={alwaysScrolledRoutes}
          // translatedPages={headerData.translatedPages}
          // pageProps={headerData.pageProps}
        />
        {children}

        <Footer
          footerMenuData={footerData.footerMenuData}
          frontPageID={footerData.frontPageID}
          options={footerData.options}
        />
      </body>
    </html>
  );
}
